# Generated by Django 3.1.12 on 2026-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Brief summary of the article', max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Hygiene', 'Hygiene'), ('Preventive Care', 'Preventive Care')], max_length=50)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
