# Generated by Django 3.1.12 on 2026-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('use', models.TextField()),
                ('dosage', models.TextField(default='As directed by physician')),
                ('side_effects', models.TextField(default='None reported')),
                ('category', models.CharField(default='General', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
