# Generated by Django 3.1.12 on 2026-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
