# Generated by Django 3.1.12 on 2026-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('specialties', models.TextField(help_text='Comma-separated specialties (e.g. Cardiology, Neurology)')),
                ('beds_available', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
            ],
        ),
    ]
